# Generated by Django 5.0.2 on 2024-02-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='pages', to='core.page'),
        ),
    ]
